site_name: Five Safes RO-Crate
site_description: An RO-Crate profile for recording and exchanging Trusted Research Environment activity
repo_url: https://github.com/eScienceLab/Five-Safes-RO-Crate
theme:
  name: readthedocs
extra_css:
  - stylesheets/extra.css
nav:
  - Specification:
      - index.md
      - Authoring Modules: authoring-modules.md
      - Quick Reference: quick-reference.md
  - Modules:
      - Cohort Discovery: modules/cohort-discovery.md
      - SafeTEXT Deidentification: modules/safetext-deidentification.md
      - Workflow Execution: modules/workflow-execution.md
plugins:
  - search
  - mermaid2
markdown_extensions:
  - admonition
  - toc:
      permalink: true
